export const SIGNIN = 'SIGNIN'
export const SIGNOUT = 'SIGNOUT'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const USER_ADMIN = 'USER_ADMIN'
export const SIGNIN_ERROR = 'SIGNIN_ERROR'
export const NEW_USER = 'NEW_USER'
export const UPDATE_USER = 'NEW_USER'
export const USER_UPDATE_USERNAME = 'USER_UPDATE_USERNAME'
export const USER_UPDATE_DNI = 'USER_UPDATE_DNI'
export const USER_UPDATE_EMAIL = 'USER_UPDATE_EMAIL'
export const USER_UPDATE_PHONE = 'USER_UPDATE_PHONE'
export const USER_UPDATE_NAME = 'USER_UPDATE_NAME'
export const USER_UPDATE_LASTNAME = 'USER_UPDATE_LASTNAME'
export const USER_UPDATE_EROLES = 'USER_UPDATE_EROLES'

export const USER_UPDATE_USERLIST = 'USER_UPDATE_USERLIST'

export const USER_SELECTED = 'USER_SELECTED'
export const USER_DESELECTED = 'USER_DESELECTED'

export const VEHICLE_SELECTED = 'VEHICLE_SELECTED'
export const VEHICLE_DESELECTED = 'VEHICLE_DESELECTED'

export const ZONE_SELECTED = 'ZONE_SELECTED'
export const ZONE_DESELECTED = 'ZONE_DESELECTED'

export const GARAGE_SELECTED = 'GARAGE_SELECTED'
export const GARAGE_DESELECTED = 'GARAGE_DESELECTED'